<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "costum_content_preview"
 *
 * Auto generated by Extension Builder 2016-05-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Better and customizable tt_content preview',
	'description' => 'Preview crop of the following tt_content elements: html, bullets, tabley',
	'category' => 'plugin',
	'author' => 'Christian Stern',
	'author_email' => 'christian.stern@pornofilm-produzent.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.9.99',
                        'flux' => '7.4.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);