<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'HTML\\Sourceopt\\Service\\CleanHtmlService' => $typo3InstallDir . 'typo3conf/ext/sourceopt/Classes/Service/CleanHtmlService.php',
    'HTML\\Sourceopt\\User\\FrontendHook' => $typo3InstallDir . 'typo3conf/ext/sourceopt/Classes/User/FrontendHook.php',
    'Mdy\\Costumcontentpreview\\ViewHelpers\\HtmlCropedPreOutput' => $typo3InstallDir . 'typo3conf/ext/costumcontentpreview/Classes/ViewHelpers/HtmlCropedPreOutputViewHelper.php',
);
